server:
  port: 8083 #

goods:
  service:
    url: http://127.0.0.1:8081/goods/

spring: 
  application:  
    name: microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:8000/eureka/  