server:
  port: 6688 #服务端口

spring: 
  application:  
    name: microservice-config #指定服务名
  cloud:  
    config:
      server:
        git: #配置git仓库地址
          uri: http://192.168.100.244:10080/config-server.git
          #username: wincentwang
          #password: wincentwang