server:
  port: 8002 #服务端口
  
spring: 
  application:  
    name: microservice-config #指定服务名
  cloud:  
    config:
      server:
        git: #配置git仓库地址
          uri: http://10.129.197.85:3000/wincentwang/config-center.git
          #username: wincentwang
          #password: wincentwang